flaskr/main/routes.py
from flask import Blueprint, request, redirect, render_template, url_for, session, jsonify
from flaskr import db, bucket
import firebase_admin
from firebase_admin import credentials, auth as firebase_auth
# import json
from firebase_admin import firestore, storage
import datetime
from datetime import datetime, timezone

import flaskr.utils.api as trefle
import uuid 
import json


main = Blueprint('main', __name__)

@main.route("/")
def home():
    # return render_template("login.html")
    # Check if user is authenticated
    # if 'uid' in session:
    #     return redirect(url_for('main.garden'))
    # return redirect(url_for('main.about'))
    if 'uid' in session:
        return redirect(url_for('main.garden')) 
    return redirect(url_for('main.about'))

@main.route('/about')
def about():
    return render_template('about.html')
#     if 'uid' in session:
#         # Get the current user
#         user = firebase_auth.get_user(session['uid'])
#         uid = session['uid']
#         return render_template('about.html', user=user)
#     else:
#         return redirect(url_for('main.about'))
    

@main.route('/login', methods=['GET', 'POST'])
def login():
    # # return render_template('login.html') 
    if 'uid' in session:
        return redirect(url_for('main.garden'))
    # if request.method == 'POST':
    #     # Handle user login logic here
    #     return redirect(url_for('main.profile'))
    return render_template('login.html')


@main.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        # Handle user signup
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')

        try:
            user = firebase_auth.create_user(
                email=email,
                password=password,
                display_name=username
            )
            # Create a user document in Firestore
            user_ref = db.collection('users').document(user.uid)
            user_ref.set({
                'username': username,
                'email': email
            })

            return jsonify({'status': 'success', 'message': 'User created successfully'}), 201
        except Exception as e:
            return jsonify({'status': 'error', 'message': str(e)}), 400

    return render_template('signup.html')

@main.route('/garden')
def garden():
    if 'uid' in session:
        # Get the current user
        user = firebase_auth.get_user(session['uid'])
        uid = session['uid']
        user_ref = db.collection('users').document(session['uid'])
        user_doc = user_ref.get()
        user_data = user_doc.to_dict()

        # Get the user's garden document from the Firestore database
        garden_ref = db.collection('garden').document(uid)
        garden_doc = garden_ref.get()

        # Initialize plant_ids as empty if no garden exists
        plant_ids = []
        my_garden = []
        potential_friends = []
        friend_request_details = []

        if garden_doc.exists:
            garden_data = garden_doc.to_dict()
            plant_ids = garden_data.get('plant_ids', [])

            for id in plant_ids:
                my_garden.append(trefle.get_species_by_id(id))

        # Get the current user's friends list
        friends_list = user_data['friends']

        # Retrieve the friend requests if they exist
        friend_reqs = user_data['friend_requests']

                
        if friend_reqs:
            # Fetch profile details for each friend request
            for requester_id in friend_reqs:
                requester_ref = db.collection('users').document(requester_id)
                requester_doc = requester_ref.get()
                if requester_doc.exists:
                    requester_data = requester_doc.to_dict()
                    friend_request_details.append({
                        'id': requester_id,
                        'profile_image': requester_data.get('profile_image', ''),  # Default to empty if no image
                        'username': requester_data.get('username', 'Unknown')      # Default if username missing
                    })

            # Get all users, excluding the current user and already friends
        users_ref = db.collection('users')
        users_query = users_ref.stream()

        # Build a list of users who are not the current user or already friends
            
        for doc in users_query:
            other_user = doc.to_dict()
            other_user_id = doc.id
                
            # Skip if the user is the current user or already a friend
            if other_user_id != uid and other_user_id not in friends_list:
                other_user['id'] = other_user_id  # Store the document ID as 'id'
                potential_friends.append(other_user)
        print(potential_friends)

        # Pass the plant_ids to the template for rendering
        return render_template('index.html', user=user_data, my_garden=my_garden, all_users=potential_friends, friend_reqs=friend_request_details)
    else:
        return redirect(url_for('main.login'))

@main.route('/session', methods=['POST'])
def create_session():
    data = request.get_json()
    id_token = data.get('token')
    if id_token:
        try:
            decoded_token = firebase_auth.verify_id_token(id_token)
            uid = decoded_token['uid']
            session['uid'] = uid
            return jsonify({'status': 'success'})
        except firebase_admin.exceptions.FirebaseError as e:
            print(e)
            return jsonify({'status': 'error', 'message': 'Invalid token'}), 400
    return jsonify({'status': 'error', 'message': 'No token provided'}), 400

@main.route('/logout', methods=['GET', 'POST'])
def logout():
    if True or request.method == 'POST':
        session.pop('uid', None)
        return redirect(url_for('main.about'))
    return redirect(url_for('main.login'))  # Fallback for GET requests


@main.route('/explore')
def profile():
    if 'uid' in session:
        user_ref = db.collection('users').document(session['uid'])
        user_doc = user_ref.get()

        if user_doc.exists:
            user_data = user_doc.to_dict()
            if 'dateJoined' in user_data:
                user_data['dateJoined'] = user_data['dateJoined'].strftime('%B %d, %Y')
            #user_data['friends_list'] = get_friends(user_data)
            all_posts = []

            if user_data['friends']: # fix
                # Reference the posts collection
                posts_ref = db.collection('posts')
                print(f"FRIENDS: {user_data['friends']}")
                for friend_id in user_data['friends']:
                    query = posts_ref.where('uid', '==', friend_id)
                    for doc in query.stream():

                        post = doc.to_dict()
                        post['id'] = doc.id  # Add the document ID to the dictionary
                        author_ref = db.collection('users').document(post['uid'])
                        author_doc = author_ref.get()
                        post['time_created_raw'] = post['time_created']  # Keep raw datetime for sorting
                        post['time_created'] = post['time_created'].strftime('%B %d, %Y')
                        print(post['time_created'])
                        post['author'] = author_doc.to_dict()
                        post['author']['id'] = author_doc.id
                        print(post['author']['id'])
                        journal_ref = db.collection('journals').document(post['journal_id'])
                        journal_doc = journal_ref.get()

                        if journal_doc.exists:
                            # Convert the document to a dictionary
                            journal_data = journal_doc.to_dict()
                            post['journal_name'] = journal_data['name']
                        else:
                            post['journal_name'] = ''
                        comments = []
                        try:    
                            for comment_id in post['comments']:
                                comment_ref = db.collection('comments').document(comment_id)
                                comment_data = comment_ref.get().to_dict()
                                comment_data['id'] = comment_id  # Include the comment document ID
                                comment_author = db.collection('users').document(comment_data['uid']).get().to_dict()
                                comment_data['author'] = comment_author
                                comments.append(comment_data)
                        except: 
                            comments = []
                        
                        post['comments'] = comments
                        all_posts.append(post)
                
            all_posts.sort(key=lambda x: x['time_created_raw'], reverse=True)  
            return render_template('profile.html', user=user_data, all_posts=all_posts)
        else:
            return redirect(url_for('main.login'))
    return redirect(url_for('main.login'))

@main.route('/friends/<friend_id>/<journal_id>')
def friend_journal(friend_id, journal_id):
    if 'uid' in session:
        user_ref = db.collection('users').document(session['uid'])
        user_doc = user_ref.get()
        user_data = user_doc.to_dict()
        friend_ref = db.collection('users').document(friend_id)
        friend_doc = friend_ref.get()
        friend_data = friend_doc.to_dict()

        journal_ref = db.collection('journals').document(journal_id)
        journal_doc = journal_ref.get()

        if journal_doc.exists:
            # Convert the document to a dictionary

flaskr/templates/_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap/css/bootstrap.min.css" media="all" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="/static/gallery/favicon.ico">
    <link rel="stylesheet" href="/static/styles.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar bordered-horizontal d-flex justify-content-between align-items-center mb-2">
        <a href="/"><h1 class="me-auto">PlantPals</h1></a>
    
        <!-- <div class="flex-grow-1 d-flex justify-content-center">
            <form id="search-form" class="d-flex" style="width: 40%;">
                <div class="input-group">
                    <input class="border-secondary rounded-pill flex-grow-1 me-2 pl-3 find-user" type="search" placeholder="Search users..." id="search-input">
                    <button class="btn-fix ml-1" type="submit">
                        <img class="nav-search" src="/static/gallery/icons/search.png" alt="Search">
                    </button>
                </div>
            </form>
        </div> -->
        <div class="dropleft">
            <a href="#" class="dropdown-toggle d-flex" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="border-right:none;">
              <img  style="border-radius: 50%; height: 3rem; width: 3rem; filter: none; box-shadow: none;" src="{{ user.photoURL }}" alt="{{ user.username }}">
            </a>
            <ul class="dropdown-menu" >
              <li><a class="nav-color" href="{{ url_for('main.journals') }}">{{ user.username }}</a></li>
              <li><a class="nav-color" href="{{ url_for('main.setting') }}">Settings</a></li>
              <li><a class="nav-color" href="{{ url_for('main.logout') }}">Logout</a></li>
            </ul>
          </div>
        
    </nav>
    
    <main>
        <div class="container-fluid">
            <div class="row ">
                <div class=" col-md-2 bordered-vertical"> <!-- Adjusted for button fitting -->
                    <ul class="nav flex-column">
                        <!--https://www.geeksforgeeks.org/flask-url-helper-function-flask-url_for/-->
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center nav-color mb-1 " href="{{ url_for('main.garden') }}">
                                <img class="nav-icon" src="/static/gallery/icons/home.png">
                                <h5 class="mb-0 px-2">Home</h5>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center nav-color mb-1" href="{{ url_for('main.add_plant') }}">
                                <img class="nav-icon" src="/static/gallery/icons/instagram-post.png">
                                <h5 class="mb-0 px-2">Garden</h5>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center nav-color mb-1" href="{{ url_for('main.journals') }}">
                                <img class="nav-icon" src="/static/gallery/icons/ribbon.png">
                                <h5 class="mb-0 px-2">Profile</h5>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center nav-color mb-1" href="{{ url_for('main.profile') }}">
                                <img class="nav-icon" src="/static/gallery/icons/explore.png">
                                <h5 class="mb-0 px-2">Explore</h5>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center nav-color mb-1" href="{{ url_for('main.new_friends') }}">
                                <img class="nav-icon " src="/static/gallery/icons/add.png">
                                <h5 class="mb-0 px-2">Friends</h5>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center nav-color mb-1" href="{{ url_for('main.setting') }}">
                                <img class="nav-icon" src="/static/gallery/icons/edit.png">
                                <h5 class="mb-0 px-2">Settings</h5>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center nav-color mb-1" href="{{ url_for('main.logout') }}">
                                <img class="nav-icon" src="/static/gallery/icons/logout.png">
                                <h5 class="mb-0 px-2">Logout</h5>
                            </a>
                        </li>

                        
                    </ul>
                </div>

                <div class="col-md-10 px-3"> <!-- Adjusted for content -->
                   
                        {% block right %}
                        {% endblock %}
                    
                </div>

                <!-- Friends section -->

                <div class=" section-friends "> 
                   
                </div>
                
            </div>
        </div>
    </main>

    <footer class="text-center py-4">
        <div class="container">
            <span>Planting Seeds and Recording Deeds!</span>
            <div class="mt-3">
                <a href="https://github.com/asteene/plant_pals" class="mx-2">Contact Us</a>
                <a href="https://facebook.com" class="mx-2" target="_blank">Facebook</a>
                <a href="https://twitter.com" class="mx-2" target="_blank">Twitter</a>
                <a href="https://instagram.com" class="mx-2" target="_blank">Instagram</a>
            </div>
            <div class="mt-3">
                <span class="mb-0">&copy; 2024 PlantPals. All rights reserved.</span>
            </div>
        </div>
    </footer>

    <script src="/static/bootstrap/jquery-3.7.1.min.js.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="/static/components/layout.js"></script>
    {% block scripts %}{% endblock %}
    
</body>
</html>

flaskr/templates/entry.html
{% extends '_layout.html' %}

{% block title %}Entry Name{% endblock %}

{% block body %}
<body>
    <header>
        <h1>Welcome to My Garden Portfolio</h1>
    </header>
    <main>
        <section>
           
        </section>
        <section>
            {% block right %}
            <h2>Entrys</h2>
            {% endblock %}
        </section>
    </main>
    
</body>
{% endblock %}

flaskr/templates/forgot_password.html
{% extends 'layout2.html' %}

{% block title %}Forget Password - PlantPals{% endblock %}

{% block left %}
    <!-- forgot_password.html -->
    <body>
      <div class="px-4">
        <h3 class="mt-1 layout-2 layout-2-font">Forgot Password</h3>
        <form id="forgot-password-form">
          <div class="form-group">
            <label class="layout-2-font" for="email">Enter your email:</label>
            <input type="email" id="email" name="email" class="form-control" required>
          </div>
          <button type="submit"  class="btn btn-primary">Send Reset Email</button>
        </form>
      
        <div id="alert"></div>
      </div>
      </body>

    <script src="https://www.gstatic.com/firebasejs/9.15.0/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/9.15.0/firebase-auth.js"></script>
    <script type="module" src="../static/components/forget.js"></script>

{% endblock %}

{% block right %}
   
{% endblock %}

flaskr/templates/friends.html
{% extends '_layout.html' %}

{% block title %}Friends- PlantPals{% endblock %}


{% block right %}
<!--Re uses the profile code.-->
<div class="d-flex justify-content-between bordered-horizontal mb-4 mt-5">
<div class="d-flex flex-column">
    <div class="d-flex flex-column">
        <div class="d-flex align-items-center mb-2">
            <img id="photo-preview" src="/static/gallery/profile.jpg" alt="Profile Photo" class="rounded-circle mt-2" width="50">
            <div class="ml-2">
                <h1 class="mb-0">Sillygoat</h1>
                <h6 class="mb-0">July 7th, 2003</h6>
            </div>
        </div>
        <div>
            <p>Blah blah blah. This is my profile description.</p>
            <p>Followed by <strong>RoseGirl</strong>, <strong>plant_wrld</strong>, <strong>Timmy</strong>, and 5 others</p>
        </div>
    </div>
</div>      
<div class="d-flex justify-content-end align-items-center pr-5">
    <div class="text-center">
        <p class="mb-0">13444</p>
        <p class="mb-0">Posts</p>
    </div>
    <div class="text-center mx-3">
        <p class="mb-0">13444</p>
        <p class="mb-0">Followers</p>
    </div>
    <div class="text-center ">
        <p class="mb-0">13444</p>
        <p class="mb-0">Following</p>
    </div>
</div>
</div>
{% for x in range(3) %}
<div class="d-flex justify-content-center mb-3 ">
    {% for y in range(4) %}
    <div class="card" style="width: 15rem;">
        <a href="/journals">
            <img src="/static/gallery/testing1.png" style="border-radius: 3%; height:15rem;" class="card-img-top" alt="...">
            
        </a>
    </div>
{% endfor %}
</div>
{% endfor %}


{% endblock %}

flaskr/templates/journals.html
{% extends '_layout.html' %}
{% block title %}Journals{% endblock %}
{% block body %}  
{% block right %}
<div class="d-flex justify-content-between bordered-horizontal mb-4 mt-5">
    {% if request.endpoint == 'main.journals' %}
        <div class="d-flex flex-column">
                <div class="d-flex align-items-center mb-4">
                    <img id="photo-preview" src="{{ user.photoURL }}" alt="Profile Photo" style="border-radius: 50%; height: 4rem; width: 4rem; filter: none; box-shadow: none;" width="50">
                    <div class="ml-2">
                        <h1 class="mb-0">{{ user.username }}</h1>
                        <h6 class="mb-0">{{ user.dateJoined }}</h6>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-end align-items-center pr-5">
                {% set ns = namespace(total_posts=0)%}
                {% for journal in journals %}
                    {% set ns.total_posts = ns.total_posts + journal.post_ids | length %}
                {% endfor %}
                
                <div class="text-center">
                    <p class="mb-0">{{ ns.total_posts }}</p>
                    <p class="mb-0">Posts</p>
                </div>
                <div class="text-center mx-3">
                    <p class="mb-0">{{ journals|length }}</p>
                    <p class="mb-0">Journals</p>
                </div>
                <div class="text-center ">
                    <p class="mb-0">{{ user['friends']|length }}</p>
                    <p class="mb-0">Friends</p>
                </div>
            </div>
        </div>
    {% elif request.endpoint == 'main.friend' %}
            <div class="d-flex flex-column">
                <div class="d-flex align-items-center mb-4">
                    <img id="photo-preview" src="{{ friend.photoURL }}" alt="Profile Photo" style="border-radius: 50%; height: 4rem; width: 4rem; filter: none; box-shadow: none;" width="50">
                    <div class="ml-2">
                        <h1 class="mb-0">{{ friend.username }}</h1>
                        <h6 class="mb-0">{{ friend.dateJoined }}</h6>
                    </div>
                </div>
              
            </div>
            <div class="d-flex justify-content-end align-items-center pr-5">
                {% set ns = namespace(total_posts=0)%}
                {% for journal in friend_journals %}
                    {% set ns.total_posts = ns.total_posts + journal.post_ids | length %}
                {% endfor %}
                
                <div class="text-center">
                    <p class="mb-0">{{ ns.total_posts }}</p>
                    <p class="mb-0">Posts</p>
                </div>
                <div class="text-center mx-3">
                    <p class="mb-0">{{ friend_journals|length }}</p>
                    <p class="mb-0">Journals</p>
                </div>
                <div class="text-center ">
                    <p class="mb-0">{{ friend['friends']|length }}</p>
                    <p class="mb-0">Friends</p>
                </div>
            </div>
        </div>
    {% endif %}
    {% if request.endpoint == 'main.journals' %}
    <div class="d-flex justify-content-end">
        <button  data-toggle="modal" data-target="#plantModal" class="btn btn-primary" style="background-color:var(--darkGreen);">Add a new Journal</button>
    </div>
    {% endif %}   
<div class="card-container d-flex flex-wrap">
    {% if request.endpoint == 'main.journals' %}
        {% for journal in journals %}
        <div class="card" style="width: 15rem;"> 
            <a href="{{ url_for('main.journal', journal_id=journal['id']) }}">
                <img class="card-img-top" src="{{ journal['image'] }}" style="border-radius: 3%; height:12rem;" alt="Plant"
                    onerror="this.onerror=null; this.src='../static/gallery/test2.jpg';">
                <div class="card-body d-flex flex-column pr-0 pl-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="card-title" style="margin-bottom: 0; text-align: left;">{{ journal['name'] | truncate(22)}}</h5>
                        <form action="{{ url_for('main.delete_journal', journal_id=journal.id) }}" method="POST">
                            <button class="btn-fix pr-1" type="submit">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </form> 
                    </div>
        
                    <!-- Sowing method and Sun requirements inline -->
                    <div class="d-flex align-items-center">
                        <div class="model" style="text-align: left; display: inline;">
                            <a href="#" data-toggle="tooltip" data-placement="top" title="{{ journal['sow'] }}">
                                <span><small>Sowing method •</small></span>
                            </a>
                        </div>
                        <span style="text-align: left; display: inline; margin-left: 8px;"> 
                            <small>{{ journal['sun'] }}</small>
                        </span>
                    </div>
                </div>
            </a>
        </div>
        
        {% endfor %}
    {% elif request.endpoint == 'main.friend' %}
        {% for friend_journal in friend_journals %}
            <div class="card" style="width: 15rem;"> 
                <a href="{{ url_for('main.friend_journal', friend_id=friend['id'], journal_id=friend_journal['id']) }}">
                <img class="card-img-top" src="{{ friend_journal['image'] }}" style="border-radius: 3%; height:12rem;" alt="Add a new journal">
                <div class="card-body d-flex justify-content-between pr-0 pl-0">
                    <h5 class="card-title" style="margin-bottom: 0; text-align: start;"> {{ friend_journal['name'] | truncate(22) }}</h5>
                    <small>#{{ friend_journal['sun'] }} • #{{ friend_journal['sow'] | truncate(23)}} </small>
                </a>
                </div>
                    
            </div>
        {% endfor %}
    {% endif %}

  
</div>
     



<div class="modal fade" id="plantModal" tabindex="-1" role="dialog" aria-labelledby="plantModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="plantModalLabel">Create Journal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="plantForm" method="POST" action="{{ url_for('main.create_journal') }}">
                    
                    <div class="form-group">
                        <input type="text" placeholder="Insert title" class="form-control" name="journal-title" name="title" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="journal-plant-id">Select Plant</label>
                        <select name='journal-plant-id' class="form-control">
                            {% for plant in my_garden %}
                                <option value="{{ plant['id'] }}">{{ plant['common_name'] }}</option>
                            {% endfor %}
                          </select>
                    </div>
               
                    <div class="form-group">
                        
                        <textarea class="form-control" placeholder="Insert description..." name="journal-description" name="description" rows="3" required></textarea>
                    </div>

                     <!-- Collapsible Content --> <!--
                     <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="addPlantCheckbox" data-toggle="collapse" data-target="#collapsibleContent">
                        <label class="form-check-label" for="addPlantCheckbox">
                          Create first post
                        </label>
                      </div>
                     <div id="collapsibleContent" class="collapse">
                        <div class="form-group">
                            <input  placeholder="Post title" type="text" class="form-control" id="post-title" name="post-title" required>
                        </div>
                        <div class="form-group">
                            <textarea  placeholder="Insert description..." class="form-control" id="post-description" name="post-description" rows="3" required></textarea>
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="file" id="formFile">
                          </div>
                    </div>
                -->
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" >Create Journal</button>
                    </div>
                </form>
            </div>
           
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
    <script type="module" src="../static/components/journals.js"></script>
 {% endblock %}

{% endblock %}

flaskr/templates/layout2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../static/bootstrap/css/bootstrap.min.css" media="all" rel="stylesheet">
    <!--Imported Google Icons & fonts-->
    <link rel="icon" type="image/x-icon" href="/static/gallery/favicon.ico">
    <link rel="stylesheet" href="/static/styles.css">
   <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    
    <script type="module" src="../static/components/layout2.js"></script>

    <nav class="navbar bordered-horizontal">
        <h1>PlantPals</h1>
    </nav>

    <main>
        <div class="container-fluid layout-bg">
            <div class="row justify-content-md-center">
                <!-- Left Sidebar -->
                <div class="col-md-3 section-center mt-4">
                    <div class="section-login my-5 py-5">
                    {% block left %}
                    <!-- Default Navigation -->
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center nav-color" href="{{ url_for('main.home') }}">
                                <span class="material-symbols-outlined material-icons">home</span>
                                <h3>Home</h3>
                            </a>
                        </li>
                        <!-- Add other navigation items similarly -->
                    </ul>
                    {% endblock %}
                </div>
                </div>

                <!-- Main Content -->
               
                    {% block right %}{% endblock %}
            
            </div>
        </div>
    </main>



    <!-- Bootstrap JS and dependencies -->
    <script src="../static/bootstrap/jquery-3.7.1.min.js.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="../static/bootstrap/js/bootstrap.bundle.js"></script>

    
</body>
</html>